### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BrahmajitMohapatra**
More polished and engaging version of readme.

### CODE REVIEW

**Comment by GauravPatil8778** [comment]
Are you here for Hactoberfest?

**Comment by BrahmajitMohapatra** [comment]
Hi Gaurav, which of your repositories are particiapting in Hactoberfest and I could commit changes also.

**Comment by GauravPatil8778** [comment]
this repo i have registred for hactober fest

**Comment by GauravPatil8778** [comment]
i have added the label

**Pull request merged**
